pipeline:
  orgIdentifier: default
  projectIdentifier: projectdemo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: jhttp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_java_app
                  name: Build Java App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn -B package --file pom.xml
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: deploytok8
          project: projectdemo
          inputs: {}
  identifier: Build_jhttp_1731943351184_Clone
  tags: {}
  name: Build and deploy jhttp on k8
