apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhttp-deployment
  labels:
    app: jhttp-app-git
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jhttp-app-git
  template:
    metadata:
      labels:
        app: jhttp-app-git
    spec:
      containers:
      - name: jhttp
        image: gcr.io/k8s-minikube/kicbase:0.0.45  # Replace with your actual image name and tag
        ports:
        - containerPort: 8888
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 15
          periodSeconds: 10
