service:
    name: jhttp-service-git
    identifier: jhttpservice-git
    spec:
      selector:  
        app: jhttp-app-git
      ports:
        - port: 80
          targetPort: 8888
          protocol: TCP
